# This configuration file is used by Travis CI to build/test TECA.

language: c

os:
  - linux
  - osx

sudo: required

dist: trusty # Ubuntu 14.04.

# Build/test only on the master branch.
branches:
  only:
    - master

compiler:
  - gcc

install: ./.install-$TRAVIS_OS_NAME-deps.sh

env:
  - BUILD_TYPE=Debug PETSC_DIR=$PWD/petsc-3.6.3 PETSC_ARCH=petsc_debug PFLOTRAN_DIR=$PWD/pflotran 
  - BUILD_TYPE=Release PETSC_DIR=$PWD/petsc-3.6.3 PETSC_ARCH=petsc_opt PFLOTRAN_DIR=$PWD/pflotran 

script: 
  - mkdir build && cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=$PWD/../alquimia-install -DCMAKE_C_COMPILER=`which mpicc` -DCMAKE_CXX_COMPILER=`which mpicxx` -DCMAKE_Fortran_COMPILER=`which mpif90` -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DXSDK_WITH_PFLOTRAN=ON -DTPL_PFLOTRAN_LIBRARIES=$PFLOTRAN_DIR/src/pflotran/libpflotranchem.a -DTPL_PFLOTRAN_INCLUDE_DIRS=$PFLOTRAN_DIR/src/pflotran
  - make -j4
  - make test
  - make install
  - cd ..

after_failure: 
  - cat build/Testing/Temporary/LastTest.log
